spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.yandex.ru
    username: misotoy@yandex.ru
    password: Oddkirill10
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  error:
    include-message: always

logging:
  file:
    name: app.log
    path: /